server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/EmployeeDB
    username: root
    password: PzqM24#03
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: false